on:
  workflow_dispatch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: Azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ secrets.RESOURCEGROUP }}
          template: .azure\infrastructure\arm.json
          parameters: .azure\infrastructure\parameter.arm.json
